# Generated by Django 3.1.4 on 2021-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0005_donation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
