# Generated by Django 3.1.4 on 2021-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0006_auto_20210123_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='dat',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
